#ifndef LIBPLDM_SMBIOS_H
#define LIBPLDM_SMBIOS_H

#ifdef __cplusplus
extern "C" {
#endif

/** @brief PLDM for SMBIOS Data Transfer Completion Code */
enum pldm_smbios_completion_codes {
	PLDM_SMBIOS_CC_INVALID_DATA_TRANSFER_HANDLE = 0x80,
	PLDM_SMBIOS_CC_INVALID_TRANSFER_OPERATION_FLAG = 0x81,
	PLDM_SMBIOS_CC_INVALID_TRANSFER_FLAG = 0x82,
	PLDM_SMBIOS_CC_INVALID_DATA_INTEGRITY_CHECK = 0x84,
	PLDM_SMBIOS_CC_SMBIOS_STRUCTURE_TABLE_UNAVAILABLE = 0x85,
	PLDM_SMBIOS_CC_NO_SMBIOS_STRUCTURES = 0x86,
	PLDM_SMBIOS_CC_INVALID_SMBIOS_STRUCTURE_TYPE = 0x87,
	PLDM_SMBIOS_CC_INVALID_SMBIOS_STRUCTURE_HANDLE = 0x88,
	PLDM_SMBIOS_CC_INVALID_SMBIOS_STRUCTURE_INSTANCE_ID = 0x89,
};

/** @brief PLDM for SMBIOS Data Transfer Command */
enum pldm_smbios_commands {
	PLDM_SMBIOS_CMD_GET_SMBIOS_STRUCTURE_TABLE_METADATA = 0x01,
	PLDM_SMBIOS_CMD_SET_SMBIOS_STRUCTURE_TABLE_METADATA = 0x02,
	PLDM_SMBIOS_CMD_GET_SMBIOS_STRUCTURE_TABLE = 0x03,
	PLDM_SMBIOS_CMD_SET_SMBIOS_STRUCTURE_TABLE = 0x04,
	PLDM_SMBIOS_CMD_GET_SMBIOS_STRUCTURE_BY_TYPE = 0x05,
	PLDM_SMBIOS_CMD_GET_SMBIOS_STRUCTURE_BY_HANDLE = 0x06,
};

#ifdef __cplusplus
}
#endif

#endif
